### ISSUE TITLE
Binary data

### ISSUE THREAD

**Issue by Athkore** [NicholasMoser/GNTool#104]
https://github.com/NicholasMoser/GNTool/blob/5eb2dd54cfa20b8bfbf913cde4936cbb47816721/src/main/java/com/github/nicholasmoser/gnt4/seq/SeqHelper.java#L318
This includes both the data for what throws, supers, z swaps, jB, jA, 8B, 8A (this is one binary blob), hp,guard (one binary blob) and data for string follow ups (another binary blob)

https://github.com/NicholasMoser/GNTool/blob/5eb2dd54cfa20b8bfbf913cde4936cbb47816721/src/main/java/com/github/nicholasmoser/gnt4/seq/SeqHelper.java#L401
This is used by op_2714

https://github.com/NicholasMoser/GNTool/blob/5eb2dd54cfa20b8bfbf913cde4936cbb47816721/src/main/java/com/github/nicholasmoser/gnt4/seq/SeqHelper.java#L435
This is a list of filenames, the first byte should probably be replaced with being op_0001 (hard_reset). The first word is only pointed to by op_0102, while the rest is pointed to by
Filename 1: op_0F0A, op_1201 (Filename for naruto: chr/loc/0000)
Filename 2: op_0F0A, op_1201 (Filename for naruto: chr/loc/0010)
Filename 3: op_0F0A, op_1303 (Filename for naruto: chr/loc/0020)
Filename 4: op_0F0A, op_1303 (Filename for naruto: mot/loc/0000)
Filename 5: op_0F0A, op_1303 (Filename for naruto: mot/cmn/0000)
Filename 6: op_0F0A, op_1303 (Filename for naruto: unite/loc/0000)
Filename 7: op_0F0A, op_1303 (Filename for naruto: mot/loc/0000)
Filename 8: op_1303 (Filename for naruto: title/0000)
Filename 9: op_0F0A (Filename for naruto: chr/cmn/1000)
Filename 10: op_5580, op_5581 (Filename for naruto: chr/loc/1300)
Filename 11: op_0F0F, op_0F11 (Filename for naruto: 0123456789abcdef0123456789abcdef)
Filename 12: op_0F0F, op_0F11 (Filename for naruto: 0123456789abcdef0123456789abcdef)
Filename 13: op_0F0F (Filename for naruto: 0123456789abcdef0123456789abcdef)
Filename 14: op_0F0F, op_0F11 (Filename for naruto: 0123456789abcdef0123456789abcdef)
Filename 15: op_0F0F, op_0F11 (Filename for naruto: 0123456789abcdef0123456789abcdef)
Filename 16: op_0F11 (Filename for naruto: 0123456789abcdef0123456789abcdef)
Filename 17: op_0F0F, op_0F11 (Filename for naruto: 0123456789abcdef0123456789abcdef)

Filenames listed seems to be universal, have not checked all characters though

https://github.com/NicholasMoser/GNTool/blob/5eb2dd54cfa20b8bfbf913cde4936cbb47816721/src/main/java/com/github/nicholasmoser/gnt4/seq/SeqHelper.java#L469
Pointer to this data is stored at offset 0x48 in chr_p

**Comment by NicholasMoser** [comment]
Oh nice! I've been meaning to go back and clean up these binary checks. I'll take a look at this sometime soon.
