### ISSUE TITLE
FPK integrity check

### ISSUE THREAD

**Issue by shadow-nero** [NicholasMoser/GNTool#162]
Some games have an integrity check of 4 Bytes, some games necessarily need these 4 Bytes 
My suggestion would be to add an option so that if the person wants to add this information to the file header 

It's not very complicated, it first takes the starting position of PRS compression and adds the bytes, Right after adding it limits the value to 16 bits
> ```
> {
>            uint newIntegridade = 0;
 >           NEWFPK.Seek(startPos, SeekOrigin.Begin);
>            while (NEWFPK.Position < endPos)
 >                  {
 >                  newIntegridade += (byte)NEWFPK.ReadByte();
>
 >                     }
  >              newIntegridade &= 0xffff;
   >              NEWFPK.Seek((long)0, SeekOrigin.Begin);
  >                          >FPKBinaryWriter.Write((uint)newIntegridade);
 > }
>```

Here is a working C# code for example:
https://github.com/shadow-nero/FPKCodes/blob/main/FPKCodes/FPKPacker.cs

**Comment by NicholasMoser** [comment]
Do you have an example of a file from a game with this integrity check? Do any files in Fate/Unlimited Codes use it?

**Comment by shadow-nero** [comment]
Yes, I have two examples Fate UC and Bleach Souls from PSP and Fate UC from PS2
For now I only found this integrity check in the FPK files of these games, the first 2 bytes being

**Comment by NicholasMoser** [comment]
I did a few quick tests and was able to add the integrity check exactly like you said, matching some Fate files I found. I'll look into adding this to the GUI soon.

**Comment by shadow-nero** [comment]
Incredible!!! Thank you very much 
I'm working on a program that will extract the texts contained in .seq, discover some opcodes and a little about how text seq works 
Once finished, if you wish, I can make this information available to add to GNTool

**Comment by NicholasMoser** [comment]
Sounds good! One day my goal is to have the SEQ interpreter working for all of the Eighting SEQ files. Right now [it only works for GNT4](https://github.com/NicholasMoser/GNTool/tree/main/src/main/java/com/github/nicholasmoser/gnt4/seq/groups), but that took a ton of work to do. Thankfully the games each have a decent bit of overlap, and you don't have to get everything correct, you just need it good enough to fully interpret the files.

**Comment by shadow-nero** [comment]
Of course, I don't know if it's the same as the other .seq but for now it's going well as far as possible
