### ISSUE TITLE
Remove X from Grab Break

### ISSUE THREAD

**Issue by NicholasMoser** [NicholasMoser/GNTool#25]
The buttons A, B, X, or Y can break grabs. When you have 0 chakra, you can mash X to easily break grabs with no downside. It would be beneficial to make it so that X no longer breaks grabs, only A, B, and Y do.

**Comment by NicholasMoser** [comment]
I have implemented this in the default branch. I just need to test it and it'll be in the next release of GNTool.

**Comment by TheCape77** [comment]
This appears to work without issue

**Comment by NicholasMoser** [comment]
This will be available in GNTool 3.7

**Comment by NicholasMoser** [comment]
https://github.com/NicholasMoser/GNTool/releases/tag/3.7

**Comment by Super-GNT4** [comment]
Update:

Make this modifiable with GNTool. Values:

0001 = forward
0002 = backward
0004 = up
0008 = down
0010 = B
0020 = A
0800 = L
1000 = R
2000 = X
4000 = Z
0200 = Y
0100 = facing left
0400 = neutral, facing right
0500 = neutral, facing left
