### ISSUE TITLE
Code adjustments

### ISSUE THREAD

**Issue by TheCape77** [NicholasMoser/GNTool#26]
Extra damage codes:
ZTK and S. Kakashi both take 1.25x
Ukon and Lee reverted to vanilla

**Comment by NicholasMoser** [comment]
I think I have it:
```
04278890 3fa00000
c203e2b0 00000003
8003001c 28000003
40820008 38000008
60000000 00000000
```

**Comment by NicholasMoser** [comment]
I added this to my list of Gecko codes for GNT4: https://github.com/NicholasMoser/Naruto-GNT-Modding/commit/1b494c56a0640ac83f838ac2bebb01f5b19213f3

Please reach out to me if there are any issues with the code. Closing
