### ISSUE TITLE
Add GNT4 Package Import Functionality 

### ISSUE THREAD

**Issue by Psi-Hate** [NicholasMoser/GNTool#28]
A function within GNTool that lets end-users to provide a GNT4 mod package to patch into their game, allowing custom mods like texture edits, custom models, and other data to be quickly applied with no need for manual file placements and the like. 

Proposed GNT4 mod package format: "*.GNTPak" or "*.zip" - a zip file with the folder structure and contents that are to be replaced. "*.GNTPak" extension for better recognition, but is optional.  

Folder structure should start in the "/files/" directory.

**Comment by NicholasMoser** [comment]
Development for this is in progress.

**Comment by NicholasMoser** [comment]
This is complete and will be released in 3.7
https://github.com/NicholasMoser/GNTool/commit/db8d67e2854fe6867937dc89f77517cc8368e166

**Comment by NicholasMoser** [comment]
Done https://github.com/NicholasMoser/GNTool/releases/tag/3.7
