### ISSUE TITLE
Training Mode Enhancements

### ISSUE THREAD

**Issue by TheCape77** [NicholasMoser/GNTool#29]
A code to make block gauge never deplete

Separated by character

**Comment by NicholasMoser** [comment]
This code should work, I'll add it to the next GNTool release.

Unlimited Block Guard
```gecko
0403f0a8 60000000
```

**Comment by NicholasMoser** [comment]
After speaking with Cape, there are some other codes that would also be useful for quicker training mode. Namely:

- Change chakra regen to be off by default (training)
- Change block to be on by default (training)
- Change character option to be controlled by 2P to be the default (training)

**Comment by NicholasMoser** [comment]
# 2P Action: 2P Control

```gecko
C2045350 00000002
38000002 B003002C
60000000 00000000
```

# Guard: ON

```gecko
04045360 B0A30030
```

# Show Inputs: OFF

```gecko
04045364 B0A30032
```

# Chakra Recovery: OFF

```gecko
04045380 B0A30040
```

**Comment by TheCape77** [comment]
These are set properly, but whenever you start up training mode they do not apply until you pause and unpause (inputs are off as is coded).

These also do not apply to Debug and would be greatly appreciated to have that as well

**Comment by NicholasMoser** [comment]
The codes should now apply in training mode without needing to pause. They also now work with debug mode. File modifications are required, specifically for `game00.seq`.

I will add this to GNTool at some point, it's just more of a hassle since it involves C2 codes.

```gecko
# 2P Action: 2P Control
c2045350 00000002
38000002 b003002c
60000000 00000000
0402e718 3bc00012
0402e728 3bc00012
In files/game/game00.seq, change 11 to 13 at offset 0x11277

# Guard: ON
04045360 B0A30030
In files/game/game00.seq, change 01 to 00 at offset 0x11287

# Show Inputs: OFF
04045364 B0A30032
C204CF8C 00000004
3FE08022 3BFF61D8
83FF221C 64000080
901F0000 80010024
60000000 00000000

# Chakra Recovery: OFF
04045380 B0A30040
In files/game/game00.seq, change C0 to 00 at offset 0x11286
```

**Comment by NicholasMoser** [comment]
The new codes have been tested and work. They also have been added to https://github.com/NicholasMoser/Naruto-GNT-Modding/blob/master/gnt4/docs/guides/gecko_codes.md#training-mode-default-2p-action-2p-control-nick

Due to the nature of the codes themselves, I don't intend on adding them to GNTool. Therefore I am closing this as complete.
