### ISSUE TITLE
Training Menus

### ISSUE THREAD

**Issue by TheCape77** [NicholasMoser/GNTool#34]
Selecting 3MC training goes to 1P training
Selecting 1P training turns on the Debug code (and off when you reset)

**Comment by NicholasMoser** [comment]
I have a code that makes 3v3 Training Mode use the Debug menu, while 1v1 Training Mode doesn't
```gecko
c2045328 00000005
9003001c 3ca08022
800561ec 28000007
40820010 3ca08005
38a5cb64 90a40008
60000000 00000000
```
Shouldn't be hard to change this to match your original request.

**Comment by NicholasMoser** [comment]
```gecko
c2045328 00000006
9003001c 3ca08022
800561ec 28000007
40820010 38000006
900561ec 48000010
3ca08005 38a5cb64
90a40008 00000000
```
This code should work.
- 3v3 training mode is 1v1 training mode with the normal menu
- 1v1 training mode is still 1v1 training mode, but with the debug menu

**Comment by TheCape77** [comment]
When leaving the Debug Training menu, if any Debug mode settings are left on (Such as FLAGs or Hitbox display) they will remain on into the game.
This was a behavior when using the Debug code in the past

If possible, when leaving the Debug Training menu it "resets" the game without the Debug features applying

**Comment by NicholasMoser** [comment]
Closing this since the original issue has been resolved, I'll give your previous comment some thought though
