### ISSUE TITLE
Default Rounds Selection

### ISSUE THREAD

**Issue by TheCape77** [NicholasMoser/GNTool#35]
In the Options Menu, the number of rounds (Kunai) to win a match is default at 2. The tournament standard is at 3.

Would like to move the default from 2 to 3.

**Comment by Super-GNT4** [comment]
Building on this:
The main menu starts at "Three Man Cell"
Please change to "Battle Mode"

This is two clicks down

**Comment by Athkore** [comment]
This action replay code at least solves the problem of default rounds selection

0022337b 00000003

**Comment by NicholasMoser** [comment]
@Athkore
I also wrote a Gecko code sets the default rounds to 3.

https://github.com/NicholasMoser/Naruto-GNT-Modding/blob/master/gnt4/docs/guides/gecko_codes.md#rounds-default-is-3

**Rounds Default is 3**

```gecko
0400b2fc b07f0192
```

@Super-GNT4 
I have written a code that makes Battle Mode the default menu option.

https://github.com/NicholasMoser/Naruto-GNT-Modding/blob/master/gnt4/docs/guides/gecko_codes.md#battle-mode-is-the-default-menu-option-nick

**Battle Mode is the Default Menu Option [Nick]**

```gecko
c20d687c 00000002
38000002 b0030000
38000000 00000000
```
