### ISSUE TITLE
Other characters

### ISSUE THREAD

**Issue by TheCape77** [NicholasMoser/GNTool#39]
Remove Akamaru from the select screen

Make Karasu on the select screen not the one Kankuro uses (so we can edit him seperately)

Add in another character that uses Karasu (off the select screen otherwise) or Oboro between A. Hinata and Naruto that works like Charade (from Soul Caliber) and picks a random fighter

**Comment by NicholasMoser** [comment]
Related issue https://github.com/NicholasMoser/GNTool/issues/23

**Comment by NicholasMoser** [comment]
There is now both random select that replaces Akamaru: https://github.com/NicholasMoser/Naruto-GNT-Modding/blob/master/gnt4/docs/guides/gecko_codes.md#add-random-select-to-character-select-screen-nick

And the ability to move characters on the screen: https://github.com/NicholasMoser/GNTool/pull/122

There isn't a way to replace Karasu currently, but this has yet to be requested again so I'm closing this.
