### ISSUE TITLE
Code ideas

### ISSUE THREAD

**Issue by TheCape77** [NicholasMoser/GNTool#4]
- Visualization and/or Audio que for counter hits (this is in CON2)

- Able to select four of the same character in 4P mode / 4 costumes
  - Increases options for 4P mode and teams. Ideally also apply to 3MC

- Remove ZTK's extra damage
  - ZTK takes 1.5x as much damage as Naruto as well as has health drain. Being able to change this value or remove it would be ideal

- Karasu taking supers for Kank drains Kank's super meter
  - Karasu takes supers for Kank, but doesn't lose meter like with normal attacks

- Game registers the analog L and R, but not the digital. Possible to make it both?
  - The soft press is registered, but the click is not

- Ability to access Training Mode Options during Debug
  - Maybe make accessing the Debug menu changed to something like C stick down or something similar and keep the training menu available. This would allow significantly more use of this mode for learning and developing counter tech

**Comment by NicholasMoser** [comment]
Some of these ideas are easier to implement than others. I will look into these and let you know what I find.

**Comment by NicholasMoser** [comment]
Some notes for myself:
- Sakon/Udon request is no longer relevant
- CON2 expresses counter hits by displaying a "Counter Hit" graphic

**Comment by NicholasMoser** [comment]
Logging issues for each of these individually:
- [Visualization and/or Audio que for counter hits (this is in CON2)](https://github.com/NicholasMoser/GNTool/issues/15)
- [Able to select four of the same character in 4P mode / 4 costumes](https://github.com/NicholasMoser/GNTool/issues/16)
- Remove ZTK's extra damage
  - This is complete and available in [GNTool 3.5](https://github.com/NicholasMoser/GNTool/releases/tag/3.5)
- [Karasu taking supers for Kank drains Kank's super meter](https://github.com/NicholasMoser/GNTool/issues/17)
- [Game registers the analog L and R, but not the digital. Possible to make it both?](https://github.com/NicholasMoser/GNTool/issues/18)
- [Ability to access Training Mode Options during Debug](https://github.com/NicholasMoser/GNTool/issues/19)
