### ISSUE TITLE
Turn off grab break while DEF or SDEF is active

### ISSUE THREAD

**Issue by Super-GNT4** [NicholasMoser/GNTool#43]
At the beginning of the victim state for all throws the following line of code appears:
Adjusting grab break window:
240C0400 00030000 is inside the .seq on the victim throw point. Changing the 03 will change the window

This turns on a DF flag "TEscape" for three frames which allows you to break a grab by inputting a face button.

What I am attempting to do is make it so that you are unable to break this grab if the victim is grabbed during a time when the AF flags DEF or SDEF are active (this may instead be DEFOK or SDEFOK). This means that during a 4A counter, a 2X super counter, or a 4B move when the guard frames are active (and the victim is currently grabbable) you would not be able to break the grab.

This was done with back grabs in Rev3 by making the grabs to the back direct instead to right after the equivalent of the above code. This can be modified for back and forward grabs already, but cannot affect the victim state as far as we know.

Facing and Back throws:
The following shows two lines of code that speak to F0 (front throw) and F1 (back throw). You can see the only difference between the two is the second half of the first word starts with 66 instead of 56 on the back throw. These locations are for Naruto
2F3C4: 00205680 00F00004 00140000 42E00000 0002F504
2F3D8: 00206680 00F10004 00140000 42E00000 0002F504

**Comment by NicholasMoser** [comment]
Starting work on this

**Comment by NicholasMoser** [comment]
Testing a code for this. In the code for opcode `240C`, it checks if that character has the `def` AF flag turned on. If they do, it ignores the grab break window. If the flag is turned off, the grab break window is set as normal.

```gecko
C20B5140 00000003
801F0128 540000C7
4082000C 5480402E
901F02F8 00000000
040b5144 60000000
```

**Comment by NicholasMoser** [comment]
Looks like the code works. I've added the code here: https://github.com/NicholasMoser/Naruto-GNT-Modding/blob/master/gnt4/docs/guides/gecko_codes.md#turn-off-grab-break-while-def-or-sdef-is-active-nick
