### ISSUE TITLE
Tsunade Confusion

### ISSUE THREAD

**Issue by Super-GNT4** [NicholasMoser/GNTool#60]
RF Flag NKawarimi (241A2D00 00000800) creates the confusion effect for Tsunade. The issue with this is it creates a random effect that either confuses buttons or directions. This would be an ideal effect if it could be controlled for example if the "punch" flag was applied (with it) it would confuse directions and if the "kick" effect was applied it would confuse buttons.

**Comment by Super-GNT4** [comment]
Update:

There are three possible outcomes:
- Swap A and B
- Swap Left and Right
- Swap X and Y

Ideally this could be done with either Punch + NKaw or Kick + NKaw and then a new flag by itself, or possibly new flags for each of the three versions

If this cannot be done, drop the Swap X + Y version and only have the two options with A + B and Left + Right

**Comment by NicholasMoser** [comment]
Spoke offline, there's actually only two states, reverse buttons or reverse movement. Will investigate controlling it via seq edits.

**Comment by NicholasMoser** [comment]
SCON4 currently determines what gets swapped by how many charges are applied. I've also written a code that allows you to choose what gets swapped based on control stick input: https://github.com/NicholasMoser/Naruto-GNT-Modding/blob/master/gnt4/docs/guides/gecko_codes.md#allow-players-to-pick-tsunade-confusion-effect-nick

Therefore I am closing this as being done.
