### ISSUE TITLE
Character Select Order

### ISSUE THREAD

**Issue by Super-GNT4** [NicholasMoser/GNTool#68]
Reorder the character select wheel to be the following:

Naruto
OTK
Sasuke
CS2
Sakura
Kakashi
Neji
Lee
TenTen
Gai
Shikamaru
Chouji
Ino
Shino
Kiba
Hinata (Shy)
Hinata (Woke)
Gaara
Temari
Kankuro
Karasu
Haku
Zabuza
Iruka
Mizuki
Anko
Sarutobi
Jiraiya
Tsunade
Orochimaru
Kabuto
Jirobo
Kidomaru
Sakon
Tayuya
Kimimaro
Itachi
Kisame
Random

**Comment by NicholasMoser** [comment]
This code should do it: https://github.com/NicholasMoser/Naruto-GNT-Modding/blob/master/gnt4/docs/guides/gecko_codes.md#add-random-select-and-reorder-css-nick
