### ISSUE TITLE
Unable to disassemble any .SEQ files in ドラえもんWii - ひみつ道具王決定戦!

### ISSUE THREAD

**Issue by SuperFromND** [NicholasMoser/GNTool#70]
So first off, I'd like to give a massive thanks to the developers of this tool; it's been incredibly useful for me for the past few days and I love how straightforward it is to use. :+1:

I've been using this tool in order to attempt to create a translation patch for the Wii game **ドラえもんWii -ひみつ道具王決定戦!-** ("**Doraemon Wii: Himitsu Douguou Ketteisen!**"), which uses .fpk and .seq files.  GNTool's FPK unpacker and repacker has helped a ton and works perfectly well for modifying the game's textures, but the .seq files (which I can only guess contains the dialog among other things) are proving to be MUCH trickier to edit.  So far, this is the only tool I can find that even claims to support this format, but unfortunately it just errors out no matter which .seq file I try to disassemble.

I don't think I can just send an example .seq, but I can provide the log:
```
Nov 19, 2021 1:27:37 AM com.github.nicholasmoser.tools.SeqDisassemblerTool$1 call
SEVERE: Error
java.lang.IllegalStateException: Soft reset should have 0 for third and fourth byte: [0, 0, 0, -98]
	at com.github.nicholasmoser@3.14.1-SNAPSHOT/com.github.nicholasmoser.gnt4.seq.groups.OpcodeGroup00.softReset(Unknown Source)
	at com.github.nicholasmoser@3.14.1-SNAPSHOT/com.github.nicholasmoser.gnt4.seq.groups.OpcodeGroup00.parse(Unknown Source)
	at com.github.nicholasmoser@3.14.1-SNAPSHOT/com.github.nicholasmoser.gnt4.seq.SeqKing.getOpcodes(Unknown Source)
	at com.github.nicholasmoser@3.14.1-SNAPSHOT/com.github.nicholasmoser.gnt4.seq.SeqKing.generateTXT(Unknown Source)
	at com.github.nicholasmoser@3.14.1-SNAPSHOT/com.github.nicholasmoser.tools.SeqDisassemblerTool$1.call(Unknown Source)
	at com.github.nicholasmoser@3.14.1-SNAPSHOT/com.github.nicholasmoser.tools.SeqDisassemblerTool$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

From what I can tell this may or may not be a dupe of #66, but I wanted to submit this as its own issue anyways just in case there ends up being something more unusual with this particular game's file formatting.

**Comment by GunBlazer** [comment]
SEQ files are instructions. They can be edited through a Hex editor.

As of now, only GNT4 SEQs can be dissasembled.

**Comment by NicholasMoser** [comment]
@SuperFromND Thanks for reaching out. As @GunBlazer said above, right now only SEQ files from Naruto GNT4 are supported. Eighting changes the format a little bit between games, so each game has to be added on a per-game basis. I am interested in exploring all of the seq formats, albeit I'm not even close to done with GNT4 😄 

Is there a specific SEQ file you'd like to disassemble or are you hoping to disassemble all of them? I could probably help getting a single one working.

I also am currently working on a feature that allows you to add new code to an SEQ file, which actually probably would work with the game you're speaking of since my changes only use the branch instruction which appears to be in all SEQ formats.

**Comment by NicholasMoser** [comment]
https://github.com/NicholasMoser/GNTool/issues/71
Created an issue to track my progress on SEQ editing in GNTool

**Comment by SuperFromND** [comment]
I'm only _really_ interested in whatever .seq files handle text (or otherwise figuring out exactly _where_ and _how_ the game stores text so it can be modified); unfortunately I don't really know which file(s) that would be due to a total lack of experience.  At an educated guess, `2d/chara_select` and `2d/final` are two possible files that might contain text or text-handling. (They correspond to the character select and "is everything ready to go?" screens respectively, both of which contain a single static line of text.)  It's completely possible I might not even be looking in the right spot, but given that the only other file formats on the disc appear to be standard ARC/BRTEX files I don't have many other ideas.

Oh, and to make things more convenient, I wrote a template for the .fpk file that stores all of these .seq files, `seq0000.fpk`.  That can be found [here,](https://pastebin.com/raw/H6eVAg03) though you'll need to add a file path as a prefix to each line.

Thanks for your help, by the way!  Very much appreciated. :D

**Comment by NicholasMoser** [comment]
This is random, but I am SO GLAD that you created this issue. I was looking into where the text is stored for Doraemon and noticed a file named `dra.MAP` on the disc. This appears to be a full symbol map of the game, possibly the only symbol map that exists of an Eighting game.

I can use this symbol map to make huge strides in my SEQ parser for the GNT games since I now have the official names of all of the SEQ parsing functions in-game (since they share **most** of their SEQ parser). This is a pretty huge discovery, an Eighting symbol map has been my holy grail for a while now.

Needless to say, I feel obligated to put in my best effort to help you with your translation issue now :)

**Comment by NicholasMoser** [comment]
So I don't have any intention of adding support for Doraemon seq parsing, but I do think I have a solution for your attempt to translate the game. First you'll want to dump the contents of the disc. You can do so with Dolphin:

![image](https://user-images.githubusercontent.com/4983605/143976336-d0ba5b4a-0a4a-44a2-8985-2cef679124f8.png)

Once you have this, you can launch the game in Dolphin using the files downloaded to your file system with File->Open and select `DATA/sys/main.dol`

To view texture files you can use [BrawlCrate](https://github.com/soopercool101/BrawlCrate) or BrawlBox. This will also allow you to translate any text that is part of a texture. Some text though will be written using bytes mapping to the font texture. These as you are aware, are in the seq files. Here I've opened the font file under `DATA/files/font/0000.brtex`

![image](https://user-images.githubusercontent.com/4983605/143976515-1e0bf384-1b55-4297-a5e4-e87d9099a128.png)

Thankfully English characters are already here, so no new textures will need to be added most likely. You can just update bytes to point to the English characters.

So let's look at the title text. I have a strong suspicion that this text is represented by bytes and not a single texture:

![image](https://user-images.githubusercontent.com/4983605/143976551-1eca8617-3e1a-4226-b5de-dca8fb249d50.png)

The last character is a period, let's figure out the likely byte that represents it. I see two potential candidates:

![image](https://user-images.githubusercontent.com/4983605/143976575-79c7341f-4af6-4fe2-85b1-86ef432ec0a5.png)

So I'm going to export this texture, modify the periods, and see which one it actually is. Then I'll assume that each character is represented by its index, and search `DATA/files/2d/title.seq` for that byte and find possible byte sequences.

Although that didn't seem to do anything after I made that change. So it must be reading from the compressed archives, the FPK files. Using GNTool, I replaced `DATA/files/fpack/cmn/0000.fpk` with the new files:

![image](https://user-images.githubusercontent.com/4983605/143976617-b108636c-fa4b-4744-9867-78017dde3e60.png)

See https://github.com/NicholasMoser/GNTool#fpk-repacker-for-wii

And after rerunning main.dol, I now can see which character it's using (albeit I broke transparency):

![image](https://user-images.githubusercontent.com/4983605/143976662-6ef35ed3-6015-462f-bf3d-14aa835e635c.png)

So here's the modified character map:

![image](https://user-images.githubusercontent.com/4983605/143976683-0c8b40db-3895-4d50-a7bd-490a9633b3ac.png)

So I tried mapping each character and it looks like it should be 0x9C

![image](https://user-images.githubusercontent.com/4983605/143976707-3354cd3f-f4d6-4ede-869a-9b8490eb3360.png)

At the beginning of title.seq I see a bunch of four-byte words that have 0x9C. I'm willing to bet that these bytes are the text:

![image](https://user-images.githubusercontent.com/4983605/143976720-6019193e-fed4-4326-aadd-4eb1b32a6eea.png)

I'm now going to replace each instance of them with 0x9E, which should be a question mark. While I'm doing that, some other interesting notes:

![image](https://user-images.githubusercontent.com/4983605/143976745-29a1222f-8b70-4d21-8c55-006c622f7f2a.png)

I'm willing to bet that 0x00000119 references the second font page, where 0x100 is the second page, 0x200 is the third page, and so on. You can see the contents of the four pages using BrawlCrate/BrawlBox. The 0x0000FFFF and 0x0000FFFE are probably ending the string, doing a newline, or a tab.
After replacing the 0x9C with 0x9E, I now need to repack the FPK file that has title.seq in it, which is `DATA/files/fpack/seq0000.fpk`:

In case it's tedious filling out each entry, you can hit the Load Template button at the bottom to load a text file with your file paths like this: https://gist.github.com/NicholasMoser/ba496c0e36aa07b5690c63f4d9d3ac6c

![image](https://user-images.githubusercontent.com/4983605/143976844-1abee880-5906-4996-bf6a-926510ceb6b6.png)

And run the game, and success!

![image](https://user-images.githubusercontent.com/4983605/143976866-593fb576-4ac5-4173-a270-6f81872ddbbe.png)

Now I have no idea which replacement affected this text, but I think it would be easy to whip up a script that reads the seq bytes and maps them to the respective character in the font map. Then it's as simple as just matching text to bytes.

Also, I presume that the seq and brtext files are loaded into memory, so you could modify the bytes in memory to test them. You can find where they are in memory by copying a bunch of bytes from one of the files and searching memory using [Dolphin Memory Engine](https://github.com/aldelaro5/Dolphin-memory-engine). Then use the Memory tab in Dolphin to modify the bytes.

![image](https://user-images.githubusercontent.com/4983605/143977669-d5009c41-9fb8-4e2a-8420-f7e13a654a29.png)

![image](https://user-images.githubusercontent.com/4983605/143977740-456cc1cf-168a-415e-8c0b-5b8ccaa57211.png)

No idea if that actually works though, it would only work if it was reloading those bytes every frame.

Hope this information helps :)

**Comment by SuperFromND** [comment]
That helps a ton!  Thank you so much! :D

**Comment by NicholasMoser** [comment]
@SuperFromND No problem. Feel free to reach out to me on Discord if you have any other questions with GameCube/Wii modding in general :)
kitesage#2355
