### ISSUE TITLE
[Feature Request] "Export Template" in FPK Repacker

### ISSUE THREAD

**Issue by SuperFromND** [NicholasMoser/GNTool#74]
A fairly self-explanatory idea; I think it'd be really useful to have an "export template" feature in the FPK repacker, alongside "load template".  When clicked, it would ask for a filename, and then save all the currently-specified file paths for the FPK to a TXT template with that filename, that can then be loaded as a template later. If a given file in the repacker isn't specified, it would instead use whatever the FPK's specified filepath is (e.g. simply writing `cmn/0000.brlyt` instead of `C:/Users/Foobar/Documents/Replacements/cmn/0000.brlyt`).  

This would be really convenient for situations involving repacking large FPKs with many files.

**Comment by NicholasMoser** [comment]
Starting work on this now.

**Comment by NicholasMoser** [comment]
@SuperFromND 
Just to confirm, this is what you're looking for right?

Here I've defined some paths.
![image](https://user-images.githubusercontent.com/4983605/148159198-e94cf691-a6f0-4426-bdd7-ca2a155b8ef6.png)

Then I have Save Template to save a new TXT file. Then I hit Load Template to load it. Now it looks like this:

![image](https://user-images.githubusercontent.com/4983605/148159221-2351f379-62bd-4252-afef-ce623f285791.png)

Look good? Feel free to make other recommendations to make this tool easier to use, I personally don't use it much lol

**Comment by SuperFromND** [comment]
Bingo! This is exactly what I needed, thank you so much!

**Comment by NicholasMoser** [comment]
This is complete. Will be released with 3.15.0 soon.

**Comment by NicholasMoser** [comment]
3.15.0 has been released https://github.com/NicholasMoser/GNTool/releases/tag/3.15.0
